language: generic

services:
 - docker

env:
 - DEPENDENCY_PACKAGES="cmake libdevhelp-dev libgail-3-dev libgee-0.8-dev libgtksourceview-3.0-dev libgtkspell-3-dev libgranite-dev libpeas-dev libsoup2.4-dev libvala-0.36-dev libvte-2.91-dev libwebkit2gtk-4.0-dev libzeitgeist-2.0 valac"

install:
 - docker pull elementary/docker:loki
 - docker run -v "$PWD":/tmp/build-dir elementary/docker:loki /bin/sh -c "apt-get update && apt-get -y install $DEPENDENCY_PACKAGES && cd /tmp/build-dir && cmake . && env CTEST_OUTPUT_ON_FAILURE=true make all test"
 - docker pull elementary/docker:loki-unstable
 - docker run -v "$PWD":/tmp/build-dir elementary/docker:loki-unstable /bin/sh -c "apt-get update && apt-get -y install $DEPENDENCY_PACKAGES && cd /tmp/build-dir && cmake . && env CTEST_OUTPUT_ON_FAILURE=true make all test"

script:
 - echo BUILDS PASSED
